name: zero2playground
# `fra` stands for Frankfurt (Germany - EU)
region: fra
services:
    -   name: zero2playground
        # Relative to the repository root
        dockerfile_path: Dockerfile
        source_dir: .
        github:
            branch: main
            deploy_on_push: true
            repo: ybastide/zero-to-playground
        health_check:
            http_path: /health_check
        # The port the application will be listening on for incoming requests
        # It should match what we specified in our configuration/production.toml file!
        http_port: 8000
        instance_count: 1
        instance_size_slug: basic-xxs
        # All incoming requests should be routed to our app
        routes:
            -   path: /
        envs:
            -   key: APP_DATABASE__USERNAME
                scope: RUN_TIME
                value: ${newsletter.USERNAME}
            -   key: APP_DATABASE__PASSWORD
                scope: RUN_TIME
                value: ${newsletter.PASSWORD}
            -   key: APP_DATABASE__HOST
                scope: RUN_TIME
                value: ${newsletter.HOSTNAME}
            -   key: APP_DATABASE__PORT
                scope: RUN_TIME
                value: ${newsletter.PORT}
            -   key: APP_DATABASE__DATABASE_NAME
                scope: RUN_TIME
                value: ${newsletter.DATABASE

databases:
    -   engine: PG
        name: newsletter
        num_nodes: 1
        size: db-s-dev-database
        version: "12"
