[application]
port = 8000

[database]
username = "postgres"
password = "password"
port = 5432
host = "localhost"
database_name = "newsletter"

[email_client]
base_url = "http://localhost"
sender_email = "test@gmail.com"
authorization_token = ""
timeout_milliseconds = 300
